In [ ]:
Hackerink Question

https://www.hackerrank.com/challenges/np-arrays/problem

In [9]:
# Solution

import numpy as np

def arrays(arr):
    return np.array(arr[::-1], float)

arr=input().strip().split(" ")
result=arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [11]:
import numpy as np

A=np.array([1, 2, 3, 4, -8, -10])
B=np.array([1, 2, 3, 4, -8, -10], float)

C=B[::-1]
print(C)

[-10.  -8.   4.   3.   2.   1.]


In [12]:
C=(A[::-1], float)
print(C)

(array([-10,  -8,   4,   3,   2,   1]), <class 'float'>)
